### PR TITLE
DM-33219: Update parameters to support gauss2dfit fitting

### PR DESCRIPTION
**Pull request by taranu**

### CODE REVIEW

**Review by TallJimbo — APPROVED** [review]
I'm a bit surprised the pointer-based comparisons are useful for anything, but I guess the context is in a package I haven't gotten to yet, so :man_shrugging: .

**Comment by taranu** [comment]
> I'm a bit surprised the pointer-based comparisons are useful for anything, but I guess the context is in a package I haven't gotten to yet, so 🤷‍♂️ .

They're pretty much exclusively to allow storage of base Parameters in `std::set`. I'm not sure how else to do it.

Besides that, I'm not sure how I'd implement a value equality comparison without putting a lot more effort into the unit system, which I'd rather not at the moment. It's not that much extra effort to write `x.get_value() == y.get_value()` if you really want to compare potentially incompatible Parameters.

**Comment by TallJimbo** [comment]
I was thinking more that if you're putting them in a set by value, each thing you add is by definition never going to compare as equal to anything else in the set because they'll have different addresses, so what are you getting out of using a set?  And if you put them in a set by some kind of smart pointer, it's that pointer's comparisons that will be used anyway.

**Comment by taranu** [comment]
Good point. I tried removing them and I misremembered - just the `<` operator is required, because `std::reference_wrapper` only implements `=`. I do use `std::set<std::reference_wrapper<parameters::ParameterBase<double>>>` a lot in gauss2dfit.

**Pull request merged**
